//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RISK.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RISK.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alaska.
        /// </summary>
        internal static string ALASKA {
            get {
                return ResourceManager.GetString("ALASKA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alberta.
        /// </summary>
        internal static string ALBERTA {
            get {
                return ResourceManager.GetString("ALBERTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central America.
        /// </summary>
        internal static string CENTRAL_AMERICA {
            get {
                return ResourceManager.GetString("CENTRAL_AMERICA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eastern United States.
        /// </summary>
        internal static string EASTERN_UNITED_STATES {
            get {
                return ResourceManager.GetString("EASTERN_UNITED_STATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greenland.
        /// </summary>
        internal static string GREENLAND {
            get {
                return ResourceManager.GetString("GREENLAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Northwest Territory.
        /// </summary>
        internal static string NORTHWEST_TERRITORY {
            get {
                return ResourceManager.GetString("NORTHWEST_TERRITORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontario.
        /// </summary>
        internal static string ONTARIO {
            get {
                return ResourceManager.GetString("ONTARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quebec.
        /// </summary>
        internal static string QUEBEC {
            get {
                return ResourceManager.GetString("QUEBEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Western United States.
        /// </summary>
        internal static string WESTERN_UNITED_STATES {
            get {
                return ResourceManager.GetString("WESTERN_UNITED_STATES", resourceCulture);
            }
        }
    }
}
