//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuiWpf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GuiWpf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afghanistan.
        /// </summary>
        internal static string AFGHANISTAN {
            get {
                return ResourceManager.GetString("AFGHANISTAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alaska.
        /// </summary>
        internal static string ALASKA {
            get {
                return ResourceManager.GetString("ALASKA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alberta.
        /// </summary>
        internal static string ALBERTA {
            get {
                return ResourceManager.GetString("ALBERTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to end game?.
        /// </summary>
        internal static string ARE_YOU_SURE_YOU_WANT_TO_END_GAME {
            get {
                return ResourceManager.GetString("ARE_YOU_SURE_YOU_WANT_TO_END_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is the winner!.
        /// </summary>
        internal static string ARG0_IS_THE_WINNER {
            get {
                return ResourceManager.GetString("ARG0_IS_THE_WINNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argentina.
        /// </summary>
        internal static string ARGENTINA {
            get {
                return ResourceManager.GetString("ARGENTINA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brazil.
        /// </summary>
        internal static string BRAZIL {
            get {
                return ResourceManager.GetString("BRAZIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central America.
        /// </summary>
        internal static string CENTRAL_AMERICA {
            get {
                return ResourceManager.GetString("CENTRAL_AMERICA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to China.
        /// </summary>
        internal static string CHINA {
            get {
                return ResourceManager.GetString("CHINA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congo.
        /// </summary>
        internal static string CONGO {
            get {
                return ResourceManager.GetString("CONGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East Africa.
        /// </summary>
        internal static string EAST_AFRICA {
            get {
                return ResourceManager.GetString("EAST_AFRICA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eastern Australia.
        /// </summary>
        internal static string EASTERN_AUSTRALIA {
            get {
                return ResourceManager.GetString("EASTERN_AUSTRALIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eastern United States.
        /// </summary>
        internal static string EASTERN_UNITED_STATES {
            get {
                return ResourceManager.GetString("EASTERN_UNITED_STATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egypt.
        /// </summary>
        internal static string EGYPT {
            get {
                return ResourceManager.GetString("EGYPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End game.
        /// </summary>
        internal static string END_GAME {
            get {
                return ResourceManager.GetString("END_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Over.
        /// </summary>
        internal static string GAME_OVER {
            get {
                return ResourceManager.GetString("GAME_OVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great Britain.
        /// </summary>
        internal static string GREAT_BRITAIN {
            get {
                return ResourceManager.GetString("GREAT_BRITAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greenland.
        /// </summary>
        internal static string GREENLAND {
            get {
                return ResourceManager.GetString("GREENLAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human.
        /// </summary>
        internal static string HUMAN {
            get {
                return ResourceManager.GetString("HUMAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iceland.
        /// </summary>
        internal static string ICELAND {
            get {
                return ResourceManager.GetString("ICELAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to India.
        /// </summary>
        internal static string INDIA {
            get {
                return ResourceManager.GetString("INDIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indonesia.
        /// </summary>
        internal static string INDONESIA {
            get {
                return ResourceManager.GetString("INDONESIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irkutsk.
        /// </summary>
        internal static string IRKUTSK {
            get {
                return ResourceManager.GetString("IRKUTSK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japan.
        /// </summary>
        internal static string JAPAN {
            get {
                return ResourceManager.GetString("JAPAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kamchatka.
        /// </summary>
        internal static string KAMCHATKA {
            get {
                return ResourceManager.GetString("KAMCHATKA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Madagascar.
        /// </summary>
        internal static string MADAGASCAR {
            get {
                return ResourceManager.GetString("MADAGASCAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle East.
        /// </summary>
        internal static string MIDDLE_EAST {
            get {
                return ResourceManager.GetString("MIDDLE_EAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mongolia.
        /// </summary>
        internal static string MONGOLIA {
            get {
                return ResourceManager.GetString("MONGOLIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral.
        /// </summary>
        internal static string NEUTRAL {
            get {
                return ResourceManager.GetString("NEUTRAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Guinea.
        /// </summary>
        internal static string NEW_GUINEA {
            get {
                return ResourceManager.GetString("NEW_GUINEA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North Africa.
        /// </summary>
        internal static string NORTH_AFRICA {
            get {
                return ResourceManager.GetString("NORTH_AFRICA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Northern Europe.
        /// </summary>
        internal static string NORTHERN_EUROPE {
            get {
                return ResourceManager.GetString("NORTHERN_EUROPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Northwest Territory.
        /// </summary>
        internal static string NORTHWEST_TERRITORY {
            get {
                return ResourceManager.GetString("NORTHWEST_TERRITORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontario.
        /// </summary>
        internal static string ONTARIO {
            get {
                return ResourceManager.GetString("ONTARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peru.
        /// </summary>
        internal static string PERU {
            get {
                return ResourceManager.GetString("PERU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place army (left: {0}).
        /// </summary>
        internal static string PLACE_ARMY {
            get {
                return ResourceManager.GetString("PLACE_ARMY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quebec.
        /// </summary>
        internal static string QUEBEC {
            get {
                return ResourceManager.GetString("QUEBEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scandinavia.
        /// </summary>
        internal static string SCANDINAVIA {
            get {
                return ResourceManager.GetString("SCANDINAVIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select territory.
        /// </summary>
        internal static string SELECT_TERRITORY {
            get {
                return ResourceManager.GetString("SELECT_TERRITORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siam.
        /// </summary>
        internal static string SIAM {
            get {
                return ResourceManager.GetString("SIAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siberia.
        /// </summary>
        internal static string SIBERIA {
            get {
                return ResourceManager.GetString("SIBERIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Africa.
        /// </summary>
        internal static string SOUTH_AFRICA {
            get {
                return ResourceManager.GetString("SOUTH_AFRICA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Southern Europe.
        /// </summary>
        internal static string SOUTHERN_EUROPE {
            get {
                return ResourceManager.GetString("SOUTHERN_EUROPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukraine.
        /// </summary>
        internal static string UKRAINE {
            get {
                return ResourceManager.GetString("UKRAINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ural.
        /// </summary>
        internal static string URAL {
            get {
                return ResourceManager.GetString("URAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venezuela.
        /// </summary>
        internal static string VENEZUELA {
            get {
                return ResourceManager.GetString("VENEZUELA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Western Australia.
        /// </summary>
        internal static string WESTERN_AUSTRALIA {
            get {
                return ResourceManager.GetString("WESTERN_AUSTRALIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Western Europe.
        /// </summary>
        internal static string WESTERN_EUROPE {
            get {
                return ResourceManager.GetString("WESTERN_EUROPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Western United States.
        /// </summary>
        internal static string WESTERN_UNITED_STATES {
            get {
                return ResourceManager.GetString("WESTERN_UNITED_STATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yakutsk.
        /// </summary>
        internal static string YAKUTSK {
            get {
                return ResourceManager.GetString("YAKUTSK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string YES {
            get {
                return ResourceManager.GetString("YES", resourceCulture);
            }
        }
    }
}
