//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlamingStrike.UI.WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlamingStrike.UI.WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afghanistan.
        /// </summary>
        public static string AFGHANISTAN {
            get {
                return ResourceManager.GetString("AFGHANISTAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alaska.
        /// </summary>
        public static string ALASKA {
            get {
                return ResourceManager.GetString("ALASKA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alberta.
        /// </summary>
        public static string ALBERTA {
            get {
                return ResourceManager.GetString("ALBERTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to end the game?.
        /// </summary>
        public static string ARE_YOU_SURE_YOU_WANT_TO_END_THE_GAME {
            get {
                return ResourceManager.GetString("ARE_YOU_SURE_YOU_WANT_TO_END_THE_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is the winner!.
        /// </summary>
        public static string ARG0_IS_THE_WINNER {
            get {
                return ResourceManager.GetString("ARG0_IS_THE_WINNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argentina.
        /// </summary>
        public static string ARGENTINA {
            get {
                return ResourceManager.GetString("ARGENTINA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack.
        /// </summary>
        public static string ATTACK {
            get {
                return ResourceManager.GetString("ATTACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brazil.
        /// </summary>
        public static string BRAZIL {
            get {
                return ResourceManager.GetString("BRAZIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central America.
        /// </summary>
        public static string CENTRAL_AMERICA {
            get {
                return ResourceManager.GetString("CENTRAL_AMERICA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to China.
        /// </summary>
        public static string CHINA {
            get {
                return ResourceManager.GetString("CHINA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congo.
        /// </summary>
        public static string CONGO {
            get {
                return ResourceManager.GetString("CONGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft Armies - Left: {0}.
        /// </summary>
        public static string DRAFT_ARMIES {
            get {
                return ResourceManager.GetString("DRAFT_ARMIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East Africa.
        /// </summary>
        public static string EAST_AFRICA {
            get {
                return ResourceManager.GetString("EAST_AFRICA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eastern Australia.
        /// </summary>
        public static string EASTERN_AUSTRALIA {
            get {
                return ResourceManager.GetString("EASTERN_AUSTRALIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eastern United States.
        /// </summary>
        public static string EASTERN_UNITED_STATES {
            get {
                return ResourceManager.GetString("EASTERN_UNITED_STATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egypt.
        /// </summary>
        public static string EGYPT {
            get {
                return ResourceManager.GetString("EGYPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Game....
        /// </summary>
        public static string END_GAME {
            get {
                return ResourceManager.GetString("END_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Turn.
        /// </summary>
        public static string END_TURN {
            get {
                return ResourceManager.GetString("END_TURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fortify.
        /// </summary>
        public static string FORTIFY {
            get {
                return ResourceManager.GetString("FORTIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Over.
        /// </summary>
        public static string GAME_OVER {
            get {
                return ResourceManager.GetString("GAME_OVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great Britain.
        /// </summary>
        public static string GREAT_BRITAIN {
            get {
                return ResourceManager.GetString("GREAT_BRITAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greenland.
        /// </summary>
        public static string GREENLAND {
            get {
                return ResourceManager.GetString("GREENLAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human.
        /// </summary>
        public static string HUMAN {
            get {
                return ResourceManager.GetString("HUMAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iceland.
        /// </summary>
        public static string ICELAND {
            get {
                return ResourceManager.GetString("ICELAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to India.
        /// </summary>
        public static string INDIA {
            get {
                return ResourceManager.GetString("INDIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indonesia.
        /// </summary>
        public static string INDONESIA {
            get {
                return ResourceManager.GetString("INDONESIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irkutsk.
        /// </summary>
        public static string IRKUTSK {
            get {
                return ResourceManager.GetString("IRKUTSK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japan.
        /// </summary>
        public static string JAPAN {
            get {
                return ResourceManager.GetString("JAPAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kamchatka.
        /// </summary>
        public static string KAMCHATKA {
            get {
                return ResourceManager.GetString("KAMCHATKA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Madagascar.
        /// </summary>
        public static string MADAGASCAR {
            get {
                return ResourceManager.GetString("MADAGASCAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle East.
        /// </summary>
        public static string MIDDLE_EAST {
            get {
                return ResourceManager.GetString("MIDDLE_EAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mongolia.
        /// </summary>
        public static string MONGOLIA {
            get {
                return ResourceManager.GetString("MONGOLIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral.
        /// </summary>
        public static string NEUTRAL {
            get {
                return ResourceManager.GetString("NEUTRAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Guinea.
        /// </summary>
        public static string NEW_GUINEA {
            get {
                return ResourceManager.GetString("NEW_GUINEA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North Africa.
        /// </summary>
        public static string NORTH_AFRICA {
            get {
                return ResourceManager.GetString("NORTH_AFRICA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Northern Europe.
        /// </summary>
        public static string NORTHERN_EUROPE {
            get {
                return ResourceManager.GetString("NORTHERN_EUROPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Northwest Territory.
        /// </summary>
        public static string NORTHWEST_TERRITORY {
            get {
                return ResourceManager.GetString("NORTHWEST_TERRITORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontario.
        /// </summary>
        public static string ONTARIO {
            get {
                return ResourceManager.GetString("ONTARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peru.
        /// </summary>
        public static string PERU {
            get {
                return ResourceManager.GetString("PERU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Army - Left: {0}.
        /// </summary>
        public static string PLACE_ARMY {
            get {
                return ResourceManager.GetString("PLACE_ARMY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player:.
        /// </summary>
        public static string PLAYER {
            get {
                return ResourceManager.GetString("PLAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0}.
        /// </summary>
        public static string PLAYER_NUMBER {
            get {
                return ResourceManager.GetString("PLAYER_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quebec.
        /// </summary>
        public static string QUEBEC {
            get {
                return ResourceManager.GetString("QUEBEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scandinavia.
        /// </summary>
        public static string SCANDINAVIA {
            get {
                return ResourceManager.GetString("SCANDINAVIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Territory.
        /// </summary>
        public static string SELECT_TERRITORY {
            get {
                return ResourceManager.GetString("SELECT_TERRITORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Territory to Attack.
        /// </summary>
        public static string SELECT_TERRITORY_TO_ATTACK {
            get {
                return ResourceManager.GetString("SELECT_TERRITORY_TO_ATTACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Territory to Move from.
        /// </summary>
        public static string SELECT_TERRITORY_TO_MOVE_FROM {
            get {
                return ResourceManager.GetString("SELECT_TERRITORY_TO_MOVE_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Territory to Move To.
        /// </summary>
        public static string SELECT_TERRITORY_TO_MOVE_TO {
            get {
                return ResourceManager.GetString("SELECT_TERRITORY_TO_MOVE_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Territory to Start the Attack from.
        /// </summary>
        public static string SELECT_TERRITORY_TO_START_THE_ATTACK_FROM {
            get {
                return ResourceManager.GetString("SELECT_TERRITORY_TO_START_THE_ATTACK_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Armies To Occupy.
        /// </summary>
        public static string SEND_ARMIES_TO_OCCUPY {
            get {
                return ResourceManager.GetString("SEND_ARMIES_TO_OCCUPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Cards....
        /// </summary>
        public static string SHOW_CARDS {
            get {
                return ResourceManager.GetString("SHOW_CARDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siam.
        /// </summary>
        public static string SIAM {
            get {
                return ResourceManager.GetString("SIAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siberia.
        /// </summary>
        public static string SIBERIA {
            get {
                return ResourceManager.GetString("SIBERIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Africa.
        /// </summary>
        public static string SOUTH_AFRICA {
            get {
                return ResourceManager.GetString("SOUTH_AFRICA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Southern Europe.
        /// </summary>
        public static string SOUTHERN_EUROPE {
            get {
                return ResourceManager.GetString("SOUTHERN_EUROPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Game.
        /// </summary>
        public static string START_GAME {
            get {
                return ResourceManager.GetString("START_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukraine.
        /// </summary>
        public static string UKRAINE {
            get {
                return ResourceManager.GetString("UKRAINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ural.
        /// </summary>
        public static string URAL {
            get {
                return ResourceManager.GetString("URAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venezuela.
        /// </summary>
        public static string VENEZUELA {
            get {
                return ResourceManager.GetString("VENEZUELA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Western Australia.
        /// </summary>
        public static string WESTERN_AUSTRALIA {
            get {
                return ResourceManager.GetString("WESTERN_AUSTRALIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Western Europe.
        /// </summary>
        public static string WESTERN_EUROPE {
            get {
                return ResourceManager.GetString("WESTERN_EUROPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Western United States.
        /// </summary>
        public static string WESTERN_UNITED_STATES {
            get {
                return ResourceManager.GetString("WESTERN_UNITED_STATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yakutsk.
        /// </summary>
        public static string YAKUTSK {
            get {
                return ResourceManager.GetString("YAKUTSK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YES {
            get {
                return ResourceManager.GetString("YES", resourceCulture);
            }
        }
    }
}
